# Generated by Django 4.2 on 2023-04-08 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('precio', models.FloatField()),
                ('existencias', models.IntegerField(default=0)),
                ('categoria_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.categoria')),
            ],
        ),
    ]
